### ISSUE TITLE
[BUG] Vertically Centered Groups missing Y-Coordinate

### ISSUE THREAD

**Issue by blackfisch** [Heyoxe/Adobe-SVG-to-Arma-Config#9]
As the title says.

If a Group is vertically centered in the project, Adobe XD omits the second number in the `translate` fiels of the SVG which results in a `NaN` as Y-position in the dialog. Should be simple to fix, PR incoming :)

**Comment by Heyoxe** [comment]
Fixed in #10 
Thank you for your contribution 😄
